# Generated by Django 5.1.7 on 2025-04-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsoolat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsoolat',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
    ]
