# Generated by Django 5.1.7 on 2025-04-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsoolat', '0002_mahsoolat_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsoolat',
            name='final_price',
            field=models.BigIntegerField(default=0),
        ),
    ]
