# Generated by Django 5.1.7 on 2025-04-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsoolat', '0005_alter_mahsoolat_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsoolat',
            name='Category',
            field=models.CharField(max_length=10),
        ),
    ]
