# Generated by Django 5.1.7 on 2025-04-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsoolat', '0006_alter_mahsoolat_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsoolat',
            name='product_type',
            field=models.CharField(choices=[('phone', 'گوشی'), ('tablet', 'تبلت'), ('console', 'کنسول'), ('laptop', 'لپتاپ'), ('accessory', 'لوازم جانبی')], default='phone', max_length=20),
        ),
    ]
