# Generated by Django 5.1.7 on 2025-04-17 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahsoolat', '0007_alter_mahsoolat_product_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mahsoolat',
            old_name='Category',
            new_name='Cry',
        ),
    ]
