# Generated by Django 5.1.7 on 2025-04-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsoolat', '0008_rename_category_mahsoolat_cry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahsoolat',
            name='Cry',
        ),
        migrations.AddField(
            model_name='mahsoolat',
            name='Categor',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
