# Generated by Django 5.1.7 on 2025-04-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahsoolat', '0009_remove_mahsoolat_cry_mahsoolat_categor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahsoolat',
            name='Categor',
        ),
    ]
