# Generated by Django 5.1.7 on 2025-04-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsoolat', '0010_remove_mahsoolat_categor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsoolat',
            name='Category',
            field=models.CharField(default='default category', max_length=50),
        ),
    ]
