# Generated by Django 5.1.7 on 2025-04-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsoolat', '0011_mahsoolat_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsoolat',
            name='Category',
            field=models.CharField(blank=True, default='default category', max_length=50, null=True),
        ),
    ]
