# Generated by Django 5.1.7 on 2025-04-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsoolat', '0012_alter_mahsoolat_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsoolat',
            name='Category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mahsoolat',
            name='hafezeh',
            field=models.CharField(default='0', max_length=7),
        ),
    ]
