# Generated by Django 5.1.7 on 2025-04-17 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahsoolat', '0013_alter_mahsoolat_category_alter_mahsoolat_hafezeh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahsoolat',
            name='Category',
        ),
    ]
