# Generated by Django 5.1.7 on 2025-04-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsoolat', '0014_remove_mahsoolat_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsoolat',
            name='Category',
            field=models.CharField(default='phone', max_length=50),
        ),
    ]
