# Generated by Django 5.1.7 on 2025-04-17 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahsoolat', '0015_mahsoolat_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahsoolat',
            name='final_price',
        ),
    ]
