# Generated by Django 5.2 on 2025-04-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsoolat', '0016_remove_mahsoolat_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsoolat',
            name='Reagen',
            field=models.CharField(default='usa', max_length=10),
        ),
    ]
