# Generated by Django 5.2 on 2025-04-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsoolat', '0018_remove_mahsoolat_category_mahsoolat_rom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsoolat',
            name='Rom',
            field=models.IntegerField(default='0'),
        ),
    ]
