# Generated by Django 5.2 on 2025-05-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsoolat', '0019_alter_mahsoolat_rom'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsoolat',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
