# Generated by Django 5.2 on 2025-05-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsoolat', '0020_mahsoolat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsoolat',
            name='image',
            field=models.ImageField(null=True, upload_to='products_img'),
        ),
    ]
