# Generated by Django 5.2 on 2025-05-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahsoolat', '0021_alter_mahsoolat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsoolat',
            name='video',
            field=models.FileField(null=True, upload_to='Media/videos'),
        ),
    ]
